services:
    phlexible_indexer_page.document_applier:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\DocumentApplier\ChainDocumentApplier
        public: false
        arguments:
            -
                - "@phlexible_indexer_page.boost_document_applier"
                - "@phlexible_indexer_page.meta_document_applier"
                - "@phlexible_indexer_page.content_document_applier"

    phlexible_indexer_page.boost_document_applier:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\DocumentApplier\BoostDocumentApplier
        public: false

    phlexible_indexer_page.content_document_applier:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\DocumentApplier\ContentDocumentApplier
        public: false
        arguments:
            - "@phlexible_element.element_service"
            - "@phlexible_indexer_page.content_filter"
            - "@phlexible_indexer_page.content_title_extractor"
            - "@phlexible_indexer_page.content_renderer"
            - "@event_dispatcher"
            - "@logger"
        tags:
            - {name: monolog.logger, channel: indexer}

    phlexible_indexer_page.meta_document_applier:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\DocumentApplier\MetaDocumentApplier
        public: false
        arguments:
            - "@phlexible_element.element_service"
            - "@phlexible_element.element_meta_set_resolver"
            - "@phlexible_element.element_meta_data_manager"
            - "@event_dispatcher"
            - "@logger"
        tags:
            - {name: monolog.logger, channel: indexer}
