services:
    phlexible_indexer_element.document_applier:
        class: Phlexible\Bundle\IndexerElementBundle\Indexer\DocumentApplier\ChainDocumentApplier
        public: false
        arguments:
            -
                - @phlexible_indexer_element.boost_document_applier
                - @phlexible_indexer_element.content_document_applier

    phlexible_indexer_element.boost_document_applier:
        class: Phlexible\Bundle\IndexerElementBundle\Indexer\DocumentApplier\BoostDocumentApplier
        public: false

    phlexible_indexer_element.content_document_applier:
        class: Phlexible\Bundle\IndexerElementBundle\Indexer\DocumentApplier\ContentDocumentApplier
        public: false
        arguments:
            - @phlexible_element.element_service
            - @phlexible_indexer_element.content_filter
            - @phlexible_indexer_element.content_title_extractor
            - @phlexible_indexer_element.content_renderer
            - @event_dispatcher
            - @logger
