services:
    phlexible_indexer_element.content_filter:
        class: Phlexible\Bundle\IndexerElementBundle\Indexer\ContentFilter\ChainContentFilter
        public: false
        arguments:
            -
                - "@phlexible_indexer_element.no_index_content_filter"
                - "@phlexible_indexer_element.html_content_filter"

    phlexible_indexer_element.no_index_content_filter:
        class: Phlexible\Bundle\IndexerElementBundle\Indexer\ContentFilter\NoIndexContentFilter
        public: false

    phlexible_indexer_element.html_content_filter:
        class: Phlexible\Bundle\IndexerElementBundle\Indexer\ContentFilter\HtmlContentFilter
        public: false
