services:
    phlexible_indexer_page.content_filter:
        class: Phlexible\Bundle\IndexerPagerBundle\Indexer\ContentFilter\ChainContentFilter
        public: false
        arguments:
            -
                - "@phlexible_indexer_page.no_index_content_filter"
                - "@phlexible_indexer_page.html_content_filter"

    phlexible_indexer_page.no_index_content_filter:
        class: Phlexible\Bundle\IndexerPagerBundle\Indexer\ContentFilter\NoIndexContentFilter
        public: false

    phlexible_indexer_page.html_content_filter:
        class: Phlexible\Bundle\IndexerPagerBundle\Indexer\ContentFilter\HtmlContentFilter
        public: false
