services:
    indexerelements.indexer:
        class: Phlexible\IndexerElementBundle\Indexer\ElementsIndexer
        arguments:
            - "@event_dispatcher"
            - "@indexerelements.storage"
            - "@doctrine.orm.entity_manager"
            - "@tree.manager"
            - "@elements.service"
            - "@elements.context.manager"
            - "%frontend.request.handler"
        tags:
            - {name: "indexer.indexer"}

    indexer.elements.query.eid:
        class: Phlexible\IndexerElementBundle\Query\EidQuery
        arguments: ["@indexer.query.parser"]
        tags:
            - {name: "indexer.search"}

    # event listeners
    indexerelements.listener.document:
        class: Phlexible\IndexerElementBundle\EventListener\DocumentListener
        tags:
            - {name: "kernel.event_listener", event: indexer.create_document, method: onCreateDocument}

    indexerelements.listener.Node:
        class: Phlexible\IndexerElementBundle\EventListener\NodeListener
        tags:
            - {name: "kernel.event_listener", event: element.create_node, method: onPublishNode}
            - {name: "kernel.event_listener", event: element.update_node, method: onUpdateNode}
            - {name: "kernel.event_listener", event: element.set_node_offline, method: onMoveNode}
            - {name: "kernel.event_listener", event: element.delete_node, method: onDeleteNode}
