services:
    phlexible_indexer_element.indexer:
        class: Phlexible\Bundle\IndexerElementBundle\Indexer\ElementIndexer
        arguments:
            - @phlexible_indexer_element.storage
            - @phlexible_indexer.document_factory
            - @phlexible_siteroot.siteroot_manager
            - @phlexible_tree.content_tree_manager.delegating
            - @phlexible_element.element_service
            - @phlexible_element_renderer.data_provider
            - @router
            - @templating
            - @event_dispatcher
            - @service_container
        tags:
            - {name: phlexible_indexer.indexer}

    phlexible_indexer_element.query.eid:
        class: Phlexible\Bundle\IndexerElementBundle\Query\EidQuery
        arguments: [@phlexible_indexer.query.parser]
        tags:
            - {name: phlexible_indexer.search}

    # event listeners
    phlexible_indexer_element.listener.Node:
        class: Phlexible\Bundle\IndexerElementBundle\EventListener\NodeListener
        tags:
            - {name: kernel.event_subscriber}
