services:
    phlexible_indexer_element.indexer:
        class: Phlexible\Bundle\IndexerElementBundle\Indexer\ElementIndexer
        arguments:
            - @phlexible_indexer_element.storage
            - @phlexible_indexer.document_factory
            - @phlexible_siteroot.siteroot_manager
            - @phlexible_tree.content_tree_manager.delegating
            - @phlexible_element.element_service
            - @phlexible_element_renderer.configurator
            - @router
            - @templating
            - @event_dispatcher
            - @logger
            - @service_container
        tags:
            - {name: phlexible_indexer.indexer}
            - {name: monolog.logger, channel: indexer}

    # event listeners
    phlexible_indexer_element.listener.Node:
        class: Phlexible\Bundle\IndexerElementBundle\EventListener\NodeListener
        arguments:
            - @phlexible_queue.job_manager
        tags:
            - {name: kernel.event_subscriber}
