services:
    phlexible_indexer_element.indexer:
        class: Phlexible\Bundle\IndexerElementBundle\Indexer\ElementIndexer
        arguments:
            - @event_dispatcher
            - @phlexible_indexer_element.storage
            - @phlexible_indexer.document_factory
            - @phlexible_siteroot.siteroot_manager
            - @phlexible_tree.tree_manager
            - @phlexible_element.element_service
            - @phlexible_element.context.manager
        tags:
            - {name: phlexible_indexer.indexer}

    phlexible_indexer_element.query.eid:
        class: Phlexible\Bundle\IndexerElementBundle\Query\EidQuery
        arguments: [@phlexible_indexer.query.parser]
        tags:
            - {name: phlexible_indexer.search}

    # event listeners
    phlexible_indexer_element.listener.document:
        class: Phlexible\Bundle\IndexerElementBundle\EventListener\DocumentListener
        tags:
            - {name: kernel.event_listener, event: phlexible_indexer.create_document, method: onCreateDocument}

    phlexible_indexer_element.listener.Node:
        class: Phlexible\Bundle\IndexerElementBundle\EventListener\NodeListener
        tags:
            - {name: kernel.event_listener, event: phlexible_element.create_node, method: onPublishNode}
            - {name: kernel.event_listener, event: phlexible_element.update_node, method: onUpdateNode}
            - {name: kernel.event_listener, event: phlexible_element.set_node_offline, method: onMoveNode}
            - {name: kernel.event_listener, event: phlexible_element.delete_node, method: onDeleteNode}
