services:
    indexerelements.indexer:
        class: Phlexible\IndexerElementsComponent\Indexer\ElementsIndexer
        arguments:
            - "@dispatcher"
            - "@indexerelements.storage"
            - "@siteroots.repository"
            - "@tree.manager"
            - "@elements.service"
            - "@elements.context.manager"
            - "%frontend.request.handler"
        tags:
            - {name: "indexer.indexer"}

    indexer.elements.query.eid:
        class: Phlexible\IndexerElementsComponent\Query\EidQuery
        arguments: ["@indexer.query.parser"]
        tags:
            - {name: "indexer.search"}

    # listeners
    indexerelements.listener.document:
        class: Phlexible\IndexerElementsComponent\Listener\DocumentListener
        tags:
            - {name: "event.listener", event: indexer.create_document, method: onCreateDocument}

    indexerelements.listener.Node:
        class: Phlexible\IndexerElementsComponent\Listener\NodeListener
        tags:
            - {name: "event.listener", event: element.create_node, method: onPublishNode}
            - {name: "event.listener", event: element.update_node, method: onUpdateNode}
            - {name: "event.listener", event: element.set_node_offline, method: onMoveNode}
            - {name: "event.listener", event: element.delete_node, method: onDeleteNode}
