services:
    indexerElementsIndexer:
        class: Phlexible\IndexerElementsComponent\Indexer\ElementsIndexer
        arguments:
            - "@dispatcher"
            - "@indexerElementsStorage"
            - "@siterootsRepository"
            - "@treeManager"
            - "@elementsService"
            - "@elementsContextManager"
            - "%frontend.request.handler"
        tags:
            - ["indexer.indexer"]

    indexerElementsQueryEid:
        class: Phlexible\IndexerElementsComponent\Query\EidQuery
        arguments: ["@indexerQueryParser"]
        tags:
            - ["indexer.search"]

    # listeners
    indexerElementsListenerDocument:
        class: Phlexible\IndexerElementsComponent\Listener\DocumentListener
        tags:
            - ["event.listener", {event: indexer.create_document, method: onCreateDocument}]

    indexerElementsListenerNode:
        class: Phlexible\IndexerElementsComponent\Listener\NodeListener
        tags:
            - ["event.listener", {event: element.create_node, method: onPublishNode}]
            - ["event.listener", {event: element.update_node, method: onUpdateNode}]
            - ["event.listener", {event: element.set_node_offline, method: onMoveNode}]
            - ["event.listener", {event: element.delete_node, method: onDeleteNode}]
